### PR TITLE
Add support for Spotify track URIs and URLs

### PR DESCRIPTION
**Pull request by rkjaer**
With this change the following slash commands would work:
* `/slackbox spotify:track:7gARZ2i5u5DHC1b1n1fML5`
* `/slackbox https://open.spotify.com/track/2UcvadWJXH3jQ3lJRA8RRu`

### CODE REVIEW

**Comment by lajlev** [comment]
:+1:

**Comment by mikefrancis** [comment]
@rkjaer Haven't got around to testing this out yet, but assuming it works I'm just wondering what the use case is for track URIs and URLs?

Our idea was to make it easy to search for songs by track or track and artist - this seems to go against that. I suppose if it works then it will do no harm merging this in, but is it really needed?

**Comment by rkjaer** [comment]
@mikefrancis The use case is to provide an explicit track. I experienced some problems with searching for remixes etc. where the wrong track came in – or even live versions. So I thought it'd be great to allow URIs and URLs as well in those cases.

Might be quite a nice-to-have feature, but I guess it makes sense to have it. :+1:

**Comment by mikefrancis** [comment]
@rkjaer Ah I see, well in that case it does make sense. I think we've got a few issues around Authorisation at the moment so once we've got those fixed we should be good to merge this in.

:+1:

**Comment by bmsdan** [comment]
@rkjaer The latest version of Slackbox now allows for a more accurate `[Artist] - [Track]` query which hopefully removes the need for this.

We'd rather focus on allowing users to handle everything through Slack; by the time they've gone to the web player to grab the Track ID or URL, it would be easier for them to add the track to their playlist from there too. 

Let us know how you get on with the new search syntax, though.

**Pull request closed without merging**
