### PR TITLE
Slack Outgoing WebHooks

### PR DESCRIPTION
**Pull request by TheConnMan**
Added support for Outgoing WebHooks so playlist additions are public within the channel. I wanted to be notified when a user added a new song and see who added it.

### CODE REVIEW

**Comment by mikefrancis** [comment]
Is this tested and working? We do plan to add automated testing at some stage but for now we will just have to take your word.

**Comment by TheConnMan** [comment]
Can't honestly say that I know anymore. I'll get a local dev env set up again and test.

**Comment by mikefrancis** [comment]
Ok cool, thanks - let us know how you get on.

**Comment by nosnaj** [comment]
Yo @TheConnMan are you just living up to your username or what? 😛

Looking forward to this!

**Comment by TheConnMan** [comment]
With a call out like that I _have_ to get back to you about this. I'll verify today.

**Comment by TheConnMan** [comment]
I've verified this still works and rebased to remove the merge conflicts.

**Comment by nosnaj** [comment]
Awesome! Really hope this gets merged. 👍 Thanks again @TheConnMan !

**Pull request merged**
